---
- hosts: all
  gather_facts: false
  vars:
    htdocs: /home/public
    url_path: rchain-dbr-beta
    install_dir: "{{ htdocs }}/{{ url_path }}"
  tasks:
    - name: check out gauth branch of rchain-dbr
      git:
        repo: https://github.com/dckc/rchain-dbr
        dest: "{{ install_dir }}"
        version: gauth
    - name: check for xataface installation
      stat:
        path: "{{ install_dir }}/xataface-2.1.3"
      register: xf
    - name: "Download xataface 2.1.3"
      get_url:
        url: https://github.com/shannah/xataface/archive/2.1.3.zip
        dest: /tmp/xataface-2.1.3.zip
        checksum: sha256:8dd8b84fdfac32a4aa2f377101f2b179ddfc7d01b26bce737938fcaea2e3458c
        validate_certs: no
      register: xf_zip
      when: not xf.stat.exists
    - name: install xataface
      unarchive:
        src: "{{ xf_zip.dest }}"
        remote_src: yes
        dest: "{{ install_dir }}"
      when: not xf.stat.exists
    - name: download PHP composer
      shell: "php composer_download.php"
      args:
        chdir: "{{ install_dir }}"
        creates: composer-setup.php
    - name: create bin directory
      file:
        path: "{{ install_dir }}/bin"
        state: directory
    - name: setup PHP composer
      shell: "php composer-setup.php --install-dir=bin --filename=composer"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/bin/composer"
    - name: compose PHP deps
      composer:
        command: install
        working_dir: "{{ install_dir }}"
      environment:
        PATH: "{{ install_dir }}/bin:/usr/local/bin:/usr/bin:/bin"
