---
- hosts: all
  gather_facts: false
  vars:
    htdocs: /home/public
    url_path: rchain-dbr-beta
    install_dir: "{{ htdocs }}/{{ url_path }}"
    xf_link: "{{ install_dir }}/xataface"
  tasks:
    - name: check out gauth branch of rchain-dbr
      git:
        repo: https://github.com/dckc/rchain-dbr
        dest: "{{ install_dir }}"
        version: gauth
    - name: check for xataface installation
      stat:
        path: "{{ xf_link }}"
      register: xf
    - name: "Download xataface 2.1.3"
      get_url:
        url: https://github.com/shannah/xataface/archive/2.1.3.zip
        dest: /tmp/xataface-2.1.3.zip
        checksum: sha256:8dd8b84fdfac32a4aa2f377101f2b179ddfc7d01b26bce737938fcaea2e3458c
        validate_certs: no
      register: xf_zip
      when: not xf.stat.exists
    - name: install xataface
      unarchive:
        src: "{{ xf_zip.dest }}"
        remote_src: yes
        dest: "{{ install_dir }}"
      when: not xf.stat.exists
    - name: link installed xataface version
      file:
        state: link
        path: "{{ xf_link }}"
        src: "{{ install_dir }}/xataface-2.1.3"
    - name: make xataface templates cache
      file:
        state: directory
        path: "{{ install_dir }}/templates_c"
        # "ensure that it is writable by the web server"
        mode: "o+rw"
    - name: check for composer
      stat:
        path: "{{ install_dir }}/bin/composer"
      register: composer_bin
    - name: create bin directory
      file:
        path: "{{ install_dir }}/bin"
        state: directory
      when: not composer_bin.stat.exists
    - name: download PHP composer
      shell: "php composer_download.php"
      args:
        chdir: "{{ install_dir }}"
      when: not composer_bin.stat.exists
    - name: setup PHP composer
      shell: "php composer-setup.php --install-dir=bin --filename=composer"
      args:
        chdir: "{{ install_dir }}"
      when: not composer_bin.stat.exists
    - name: compose PHP deps
      composer:
        command: install
        working_dir: "{{ install_dir }}"
      environment:
        PATH: "{{ install_dir }}/bin:/usr/local/bin:/usr/bin:/bin"
    - name: install XDB module
      synchronize:
        src: "{{ install_dir }}/xataface_template/modules/"
        dest: "{{ xf_link }}/modules/"
      delegate_to: "{{ inventory_hostname }}"
    - name: fill in conf.ini template
      template:
        src: "conf.ini.example"
        dest: "{{ install_dir }}/conf.ini"
